// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product_Service.Data;

#nullable disable

namespace Product_Service.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Product_Service.Models.Entities.ProductEntity", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ProductCategory", "Product_Service.Models.Entities.ProductEntity.ProductCategory#Category", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("OriginalValue")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Product_Service.Models.Entities.ProductEntity", b =>
                {
                    b.OwnsOne("Product_Service.Models.Domain.ProductSizes", "ProductSizes", b1 =>
                        {
                            b1.Property<int>("ProductEntityProductId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("L")
                                .HasColumnType("INTEGER")
                                .HasColumnName("L");

                            b1.Property<bool>("M")
                                .HasColumnType("INTEGER")
                                .HasColumnName("M");

                            b1.Property<bool>("S")
                                .HasColumnType("INTEGER")
                                .HasColumnName("S");

                            b1.Property<bool>("XL")
                                .HasColumnType("INTEGER")
                                .HasColumnName("XL");

                            b1.Property<bool>("XS")
                                .HasColumnType("INTEGER")
                                .HasColumnName("XS");

                            b1.Property<bool>("XXL")
                                .HasColumnType("INTEGER")
                                .HasColumnName("XXL");

                            b1.HasKey("ProductEntityProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductEntityProductId");
                        });

                    b.Navigation("ProductSizes")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
